# Generated by Django 3.0.5 on 2020-04-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.shutterstock.com/image-vector/coming-soon-page-design-fried-egg-1263883669', max_length=500),
        ),
    ]
