# Generated by Django 3.0.5 on 2020-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_auto_20200412_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Pizza awesome', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Pizza', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=100),
        ),
    ]
