# Generated by Django 3.0.5 on 2020-04-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.shutterstock.com/image-photo/cinema-concept-red-striped-boxes-600w-1371235550.jpg', max_length=500),
        ),
    ]
