# Generated by Django 3.0.5 on 2020-04-18 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodApp', '0005_auto_20200415_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('message', models.CharField(max_length=700)),
                ('customer_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
