# Generated by Django 3.0.5 on 2020-04-18 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodApp', '0006_postcontactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontactinfo',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcontactinfo',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
    ]
