# Generated by Django 3.0.5 on 2020-04-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_auto_20200418_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontactinfo',
            name='user_name',
        ),
    ]
