# Generated by Django 3.0.5 on 2020-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0009_postcontactinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontactinfo',
            name='customer_name',
            field=models.CharField(db_column='Customer Name', max_length=200),
        ),
    ]
