# Generated by Django 3.0.5 on 2020-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0010_auto_20200418_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontactinfo',
            name='email_id',
            field=models.CharField(db_column='Email Id', max_length=200),
        ),
        migrations.AlterField(
            model_name='postcontactinfo',
            name='message',
            field=models.CharField(db_column='Message', max_length=700),
        ),
        migrations.AlterField(
            model_name='postcontactinfo',
            name='mobile_no',
            field=models.IntegerField(db_column='Mobile No'),
        ),
    ]
