# Generated by Django 3.0.5 on 2020-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0011_auto_20200418_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontactinfo',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postcontactinfo',
            name='email_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postcontactinfo',
            name='message',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='postcontactinfo',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
