# Generated by Django 3.0.5 on 2020-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0012_auto_20200418_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontactinfo',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
